version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8npasselev@2025
      POSTGRES_DB: n8n
    volumes:
      - n8n_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    volumes:
      - redis_data:/data

  n8n-web:
    image: n8nio/n8n:1.85.1
    restart: always
    ports:
      - "5678:5678"
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: n8npasselev@2025

      QUEUE_MODE: true
      QUEUE_HEALTH_CHECK_ACTIVE: true
      QUEUE_REDIS_HOST: redis
      QUEUE_REDIS_PORT: 6379

      N8N_ENCRYPTION_KEY: "b3f9c8a1e5d74f0a9b7c6d1f2e8a3c4d"
      N8N_BASIC_AUTH_ACTIVE: true
      N8N_BASIC_AUTH_USER: admin
      N8N_BASIC_AUTH_PASSWORD: adminpass

      N8N_HOST: n8n.local
      WEBHOOK_URL: http://localhost:5678
      GENERIC_TIMEZONE: America/Sao_Paulo

    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - postgres
      - redis

  n8n-worker:
    image: n8nio/n8n:1.85.1
    restart: always
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: n8npasselev@2025

      QUEUE_MODE: true
      QUEUE_REDIS_HOST: redis
      QUEUE_REDIS_PORT: 6379

      N8N_ENCRYPTION_KEY: "b3f9c8a1e5d74f0a9b7c6d1f2e8a3c4d"
      GENERIC_TIMEZONE: America/Sao_Paulo

      EXECUTIONS_CONCURRENCY: 5
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: true
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - postgres
      - redis

  n8n-webhook:
    image: n8nio/n8n:1.85.1
    restart: always
    ports:
      - "5679:5678"
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: n8npasselev@2025

      QUEUE_MODE: true
      QUEUE_REDIS_HOST: redis
      QUEUE_REDIS_PORT: 6379

      N8N_ENCRYPTION_KEY: "b3f9c8a1e5d74f0a9b7c6d1f2e8a3c4d"
      N8N_HOST: n8n.local
      WEBHOOK_URL: http://localhost:5679
      GENERIC_TIMEZONE: America/Sao_Paulo
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - postgres
      - redis

volumes:
  n8n_data:
  n8n_postgres_data:
  redis_data:
 
